name: Bun CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "🧾 Checkout code"
        uses: actions/checkout@v3

      - name: "🥐 Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Verify TypeScript
        run: bun tsc --noEmit

      - name: Check formatting
        if: always()
        run: bunx biome format

      - name: Lint code
        if: always()
        run: bunx biome lint .

      - name: Run tests
        if: always()
        run: bun test
