name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: windows-latest
            platform: win
            arch: x64
          - os: macos-latest
            platform: darwin
            arch: x64

    steps:
      - name: "🧾 Checkout code"
        uses: actions/checkout@v3

      - name: "🧅 Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: "👷 Building project"
        run: |
          bun build ./src/cli.ts --compile --outfile summarizer-${{ matrix.platform }}-${{ matrix.arch }}
        shell: bash

      - name: Adjust file names for Windows
        if: matrix.os == 'windows-latest'
        run: |
          ren summarizer-*.exe summarizer-${{ matrix.platform }}-${{ matrix.arch }}.exe
        shell: cmd

      - name: "📦 Upload release asset"
        run: |
          cd ${{ github.workspace }}
          gh release upload ${{ github.event.release.tag_name }} summarizer-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
